### ISSUE TITLE
wpt-pr-bot exceeding GitHub API limit

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt-pr-bot#144]
See https://github.com/web-platform-tests/wpt.live/issues/26, where this impacted a different service performed by wpt-pr-bot.

Currently we seem to be cresting right at the edge of the API limit (5000 requests an hour), such that if the timing of the WebKit sync code happens once more in an hour then we will go over. This occurs rarely, but is still something we should be very cautious of.

```
2020-02-11T12:03:43.060727Z GET https://api.github.com/repos/web-platform-tests/wpt/issues/15431 
2020-02-11T12:03:43.107724Z Error: API rate limit exceeded for user ID 16780864.
    at errFrom (/srv/lib/github.js:10:15)
    at Request.onResponse [as _callback] (/srv/lib/github.js:87:29)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12) { 
2020-02-11T12:03:43.107745Z   statusCode: 403 
2020-02-11T12:03:43.107755Z } 
```

As an quick fix for https://github.com/web-platform-tests/wpt.live/issues/26, I plan to drop the WebKit sync schedule to once every 15 minutes (current once every 5), which should be the bulk of API requests. Then we need to look at the code, and see if we can reduce how often we call GitHub APIs.

**Comment by gsnedders** [comment]
Looking at where we call [`github.get`](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt-pr-bot%20github.get&type=code), If we believe the [webhook event docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request) and the "[Get a pull request](https://docs.github.com/en/rest/pulls/pulls?actionType=synchronize&versionId=free-pro-team%40latest&apiVersion=2022-11-28#get-a-pull-request)" endpoint docs, the majority of our calls could be replaced with a single "get a pull request" call.
