### ISSUE TITLE
wpt-pr-bot missed a webhook - reviewer missing 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-pr-bot#48]
https://github.com/web-platform-tests/wpt/pull/13693 Missing a review when the PE is created

**Comment by jugglinmike** [comment]
Thanks for the report! The only change in the referenced pull request is a file deletion. That's fairly unique, so it initially seemed like an edge case we weren't handling properly. However, running the code against that pull request right now yields the expected result.

The logs have this to say:

    Oct 24 01:06:13 wpt-pr-bot app/web.1: #13693 pull request opened 
    Oct 24 01:06:14 wpt-pr-bot heroku/router: at=info method=POST path="/github-hook" host=wpt-pr-bot.herokuapp.com request_id=0000000 fwd="192.30.252.45" dyno=web.1 connect=1ms service=4ms status=200 bytes=224 protocol=https 
    Oct 24 01:06:14 wpt-pr-bot app/web.1: #13693: not handled. action: labeled isComment: false 
    Oct 24 01:06:18 wpt-pr-bot app/web.1: GET https://api.github.com/repos/web-platform-tests/wpt/pulls/13693/files 
    Oct 24 01:06:18 wpt-pr-bot app/web.1: #13693: THIS SHOULDN'T EVER HAPPEN 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:  Error: Not Found 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at errFrom (/app/lib/github.js:10:15) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at Request.onResponse [as _callback] (/app/lib/github.js:86:29) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at Request.self.callback (/app/node_modules/request/request.js:372:22) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at emitTwo (events.js:126:13) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at Request.emit (events.js:214:7) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at Request.<anonymous> (/app/node_modules/request/request.js:1317:14) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at emitOne (events.js:121:20) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at Request.emit (events.js:211:7) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1265:12) 
    Oct 24 01:06:18 wpt-pr-bot app/web.1:     at emitNone (events.js:111:20) 

The requested resource is available now, so this may have been the result of a transient network connectivity issue.

**Comment by zcorpan** [comment]
Interesting. That error was the reason for filing https://github.com/web-platform-tests/wpt/issues/13710 so possibly the guess (by @tobie) at the cause was incorrect.

Maybe the code could retry after a timeout if the problem is connectivity?

**Comment by jugglinmike** [comment]
> That error was the reason for filing https://github.com/web-platform-tests/wpt/issues/13710 so possibly the guess (by @tobie) at the cause was incorrect.

The string "THIS SHOULDN'T EVER HAPPEN" is logged in response many distinct errors. Although this particular case is unrelated to user permissions, Tobie's diagnosis was for other cases which are caused by permissions. So unfortunately, https://github.com/web-platform-tests/wpt/issues/13710 is still a valid bug.

> Maybe the code could retry after a timeout if the problem is connectivity?

It could! https://github.com/web-platform-tests/wpt-pr-bot/pull/49
